### ISSUE TITLE
Persistent storage and manifest.json

### ISSUE THREAD

**Issue by canDry** [davidahmed/wiper#2]
A couple issues..
i) when I close down firefox (v76) the stored blacklist gets wiped.  My settings allow cookies and do not wipe them upon closing.  
ii) the manifest.json in your addon won't work with any of the recent versions.  It's missing:
```
    "applications": {
        "gecko": {
            "id": "xxx@yyy.com"
        }
    },
```

iii) lastly, the toolbar icon doesn't appear to do anything?  Perhaps it could open the blacklist panel (and create a new tab with google)?
  
Nice little tool for filtering out results.  Thanks!

**Comment by davidahmed** [comment]
On point iii)- No, currently the blacklist panel list is only accessible via View>Sidebar>Wiper
I'll try to reproduce (i),
and thanks for the tip in (ii)- I'll fix it and update here.

**Comment by davidahmed** [comment]
You were right, and I'm sorry that (i) never happened to me since I didn't restart my firefox for months (!!!), but you were correct. Commit fc8c7b9eb2df38f1eb6495f484e5afb92d1a7475 fixes it.

Regarding (iii), please check the latest release on the Firefox addons (just update you extension if it's not set to update automatically).

Unfortunately, I can't reproduce (ii). If it persists, please feel free to open another issue. Thanks!
